[[keyboard.bindings]]
action = "CreateNewWindow"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "none"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;2H"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2F"
key = "End"
mods = "Shift"

[window]
padding = { x = 3, y = 0 }
dimensions = { columns = 86, lines = 24 }
dynamic_title = true

[font]
size = 6.5

[colors.primary]
background = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
