[general]
working_directory = "C:/Users/aman.v/"

[terminal]
# shell = { program = "bash" }

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
key = "`"
mods = "Control"
chars = '†'

[window]
dynamic_title = true

[colors.primary]
background = '#32302f'
foreground = '#ebdbb2'
